app:
  baseUrl: https://${BACKSTAGE_URL}

backend:
  baseUrl: https://${BACKSTAGE_URL}
  cors:
    origin: https://${BACKSTAGE_URL}
  auth:
    keys:
      - secret: ${BACKEND_AUTH_SECRET}
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}
      ssl: true
  reading:
    allow:
      - host: github.com
      - host: raw.githubusercontent.com
